title: make-u-topia.
url: "https://mak4026.github.io"
baseurl:
google_analytics_key: UA-106388908-2
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: まけトピアのポートフォリオ

# Author details for the jekyll-seo-tag gem
author:
  name: maktopia
  email:
  twitter: White_mak4026 # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: maktopia
  links:
    - https://github.com/mak4026
    - https://twitter.com/White_mak4026

twitter:
  username: White_mak4026
  card: summary

lang: ja_JP
timezone: Asia/Tokyo

collections:
  clients:
    output: true
    permalink: "works/:path"

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      sort_num: 0
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      image: /images/profile.png

# -----------
# CloudCannon

social_icons:
  - Twitter
  - YouTube
